version: "3.8"
services:
  elasticsearch:
    container_name: "elasticsearch-deck"
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.5.2"
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    networks:
      - elastic
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: "kibana-deck"
    image: docker.elastic.co/kibana/kibana:8.5.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-deck:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
